# A complicated setup of kafka cluster + 1 producer + 2 consumers

version: "3.3"

volumes:
  zk_data:
    driver: local

services:
  zookeeper:
    image: confluent/zookeeper
    volumes:
      - zk_data:/tmp/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888

  kafka1:
    image: confluent/kafka
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9091:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - ZOOKEEPER=zookeeper:2181
      # Create needed topics
      - KAFKA_CREATE_TOPICS=testtopic:1:3

  kafka2:
    image: confluent/kafka
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - ZOOKEEPER=zookeeper:2181

  kafka3:
    image: confluent/kafka
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=3
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - ZOOKEEPER=zookeeper:2181

  producer:
    image: isdemidoff-kafka-producer-test
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8000:8000"
    environment:
      kafka.bootstrapAddress: "kafka1:9092,kafka2:9092,kafka3:9092"

  consumer1:
    image: isdemidoff-kafka-consumer-test
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8001:8001"
    environment:
      kafka.bootstrapAddress: "kafka1:9092,kafka2:9092,kafka3:9092"
      kafka.groupId: "testgroup1"

  consumer2:
    image: isdemidoff-kafka-consumer-test
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8002:8001"
    environment:
      kafka.bootstrapAddress: "kafka1:9092,kafka2:9092,kafka3:9092"
      kafka.groupId: "testgroup2"
